name: Publish Docs

concurrency:
  group: PublishDocs
  cancel-in-progress: true

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  install:
    uses: KL-Engineering/github-action-workflows/.github/workflows/npm-ci.yml@v3.3.0
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    environment: latest
    needs: [install]
    steps:
      - uses: nschloe/action-cached-lfs-checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Find node_modules cache
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          
      - name: Build Docs
        run: npm run docs
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

  confirm-deploy:
    needs: [deploy]
    runs-on: ubuntu-latest
    environment: latest
    steps:
      - name: Debug message
        run: echo Docs finished deploying
