name: Pull requests

on:
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    install:
        uses: KL-Engineering/github-action-workflows/.github/workflows/npm-ci.yml@v3.3.0
        secrets:
            NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

    build:
        needs: [install]
        uses: KL-Engineering/github-action-workflows/.github/workflows/npm-build-upload-package.yml@v3.3.0